spring:
  
      jpa:
          hibernate:
            ddl-auto: validate
          properties:
            hibernate:
              hibernate.enable_lazy_load_no_trans: true
              show_sql: true
              use_sql_comments: true
              format_sql: true

      datasource:
           url: jdbc:mysql://localhost:3306/gestiongarages?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
           username: root
           password:
